Headers
ColdWeatherBoyy/dead-inside-games pull request #34
Opened 2023-03-22 17:24 UTC by Dev-Devin

❗ Please **DO NOT** open a Pull Request without creating an Issue first. Failure to do so will result in the rejection of the pull request.

## Purposegit 
creating boiler plate for each of the headers
Fixes #[issue]

Please provide a detailed explanation of the PR. What existing problem does it solve?
n/a
## Changes
n/a
Please provide an overview of code changes, especially key files and areas of significant change.
everything is stored in headers folder
path/to/file
headers
- change
- change
- change

## Steps to Reproduce or Test
n/a
Demonstrate that the pull request is functional. For example: the exact commands to be run and their output; screenshots if the PR modifies the UI.
n/a
## Optional GIF of screenshot

Self-explanatory.

2023-03-22 18:28 UTC, ColinSprows approved these changes

2023-03-22 18:30 UTC, ColinSprows requested changes
It also looks like you need to situate your env.Example file and potentially fix conflict in package.json

2023-03-23 13:52 UTC, ColdWeatherBoyy approved these changes
Looking good!

2023-03-23 13:53 UTC, ColinSprows approved these changes
Approved as per elias

2023-03-23 13:54 UTC, merged